version: '3.5'
services:
  main-nginx:
    image: nginx:1.23.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/www:/var/www/default
    networks:
      - webnet

  main-certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - webnet
      
networks:
  proxynet:
    name: webnet